AWSTemplateFormatVersion: 2010-09-09
Description: WordPress Middle Scale Architecture RDS
Parameters:
  PrivateSubnetId1:
    Description: Subnet 1 for RDS Subnet Group
    Type: String
  PrivateSubnetId2:
    Description: Subnet 2 for RDS Subnet Group
    Type: String
  DBSecurityGroup:
    Description: Security Group for DB
    Type: String
  DBInstanceIdentifier:
    Description: RDS DB Instance Identifire
    Type: String
    Default: 'wordpressdb'
  DBEngineVersion: 
    Description: DB Engine Version
    Type: String
    Default: '5.7.22'
  DBInstanceClass:
    Description: DB Instance Class
    AllowedValues:
      - db.t2.micro
      - db.t2.small
      - db.t2.medium
      - db.r3.large
      - db.r3.xlarge
      - db.r3.2xlarge
      - db.r3.4xlarge
      - db.r3.8xlarge
      - db.r4.large
      - db.r4.xlarge
      - db.r4.2xlarge
      - db.r4.4xlarge
      - db.r4.8xlarge
      - db.r4.16xlarge
    ConstraintDescription: Must be a valid RDS instance class.
    Default: db.t2.micro
    Description: The Amazon RDS database instance class.
    Type: String
  DBName:
    AllowedPattern: ^([a-zA-Z0-9]*)$
    Description: The Amazon RDS master database name.
    Default: 'wordpress'
    Type: String
  BackupRetentionPeriod:
    Description: DB Backup Retention Period
    Type: String
    Default: '7'
  DBRestoreSnapshotArn:
    Description: DB Restore Snapshot ARN
    Default: ''
    Type: String
  DBEncrpytedBoolean:
    AllowedValues:
      - true
      - false
    Default: false
    Description: Indicates whether the DB instances are encrypted.
    Type: String
  DBMultiAZBoolean:
    AllowedValues:
      - true
      - false
    Default: false
    Description: Indicates whether the DB instances are mauti-az.
    Type: String
Conditions:
  NoSnapshot:
    !Equals ['', !Ref DBRestoreSnapshotArn]
Resources:
  WordPressRDSSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Description: "This is a Secrets Manager secret for an RDS DB instance"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludePunctuation: 'true'
  SecretRDSInstanceAttachment:
    Type: "AWS::SecretsManager::SecretTargetAttachment"
    Properties:
      SecretId: !Ref WordPressRDSSecret
      TargetId: !Ref WordPressRDS
      TargetType: AWS::RDS::DBInstance
  WordPressDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: 'DBSubnet Group for Wordpress DB'
      SubnetIds:
        - !Ref PrivateSubnetId1
        - !Ref PrivateSubnetId2
      Tags:
        - Key: Name
          Value: !Join 
            - '-'
            - - !Ref 'AWS::StackName'
              - DBSubnetGroup
  WordPressRDS: 
    Type: AWS::RDS::DBInstance
    Properties: 
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      StorageType: 'gp2'
      AllocatedStorage: '20'
      DBInstanceClass: !Ref DBInstanceClass
      Engine: 'MySQL'
      EngineVersion: !Ref DBEngineVersion
      DBSnapshotIdentifier: !If [ NoSnapshot, !Ref 'AWS::NoValue', !Ref DBRestoreSnapshotArn]
      DBName: !If [ NoSnapshot, !Ref DBName, !Ref 'AWS::NoValue']
      MasterUsername: !If [ NoSnapshot, !Join ['', ['{{resolve:secretsmanager:', !Ref WordPressRDSSecret, ':SecretString:username}}' ]], !Ref 'AWS::NoValue']
      MasterUserPassword: !If [ NoSnapshot, !Join ['', ['{{resolve:secretsmanager:', !Ref WordPressRDSSecret, ':SecretString:password}}' ]], !Ref 'AWS::NoValue']
      DBSubnetGroupName: !Ref WordPressDBSubnetGroup
      CopyTagsToSnapshot: 'true'
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      MultiAZ: !Ref DBMultiAZBoolean
      StorageEncrypted: !If [ NoSnapshot, !Ref DBEncrpytedBoolean, !Ref 'AWS::NoValue']
      VPCSecurityGroups: 
        - !Ref DBSecurityGroup
      Tags:
        - Key: Name
          Value: !Join 
            - '-'
            - - !Ref 'AWS::StackName'
              - RDB
    DeletionPolicy: 'Snapshot'
Outputs:
  RDSSecret:
    Value: !Ref WordPressRDSSecret
    Description: WordPressRDS Secret
  RDSEndpointAddress:
    Value: !GetAtt WordPressRDS.Endpoint.Address
    Description: WordPressRDS Endpoint address
  RDSEndpointPort:
    Value: !GetAtt WordPressRDS.Endpoint.Port
    Description: WordPressRDS Endpoint Port
